validate envs

diff --git a/.github/workflows/stage.yaml b/.github/workflows/stage.yaml
--- a/.github/workflows/stage.yaml
+++ b/.github/workflows/stage.yaml
@@ -13,6 +13,18 @@ jobs:
     deploy:
         runs-on: macos-latest
         steps:
-            - name: "test env values"
+            - name: "Check environment variables"
               run: |
-                  echo ${{ secrets.ENV }}
+                  if [ -z "${{ secrets.CUSTOM_LOCAL }}" ]; then
+                      echo "Error: CUSTOM_LOCAL is not set or is empty."
+                      exit 1
+                  fi
+                  if [ -z "${{ secrets.DOMAIN }}" ]; then
+                      echo "Error: DOMAIN is not set or is empty."
+                      exit 1
+                  fi
+                  if [ -z "${{ secrets.ENV }}" ]; then
+                      echo "Error: ENV is not set or is empty."
+                      exit 1
+                  fi
+                  echo "All required secrets are set."
